config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  resources :products

  root 'products#index'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  validates :first_name,  presence: true
  validates :last_name,   presence: true
  validates :birthday,    presence: true
  validates :avatar,       attachment_presence: true
  validates :passport,       attachment_presence: true

  has_attached_file :avatar, styles: { large: "600x600>", medium: "300x300>", thumb: "150x150#" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  has_attached_file :passport, styles: { large: "600x600>", medium: "300x300>", thumb: "150x150#" }
  validates_attachment_content_type :passport, content_type: /\Aimage\/.*\Z/

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, password_length: 10..128
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user

  validates :name,        presence: true
  validates :description, presence: true
  validates :image,       attachment_presence: true

  has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb: "150x150#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def auth_user!(opts = {})
    if admin_signed_in?
      authenticate_admin!
    else
      authenticate_user!
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:name, :first_name, :last_name, :birthday, :avatar, :passport]
    devise_parameter_sanitizer.for(:account_update) << [:name, :first_name, :last_name, :birthday, :avatar, :passport]
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: [:show, :edit, :update]
  before_action :auth_user!, except: [:index, :show]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = current_user.products.build
  end

  def create
    @product = current_user.products.build(product_params)
    if @product.save
      redirect_to @product
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to @product
    else
      render 'edit'
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :image, :is_pro)
  end

  def find_product
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "ProductsGrid", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Products", products_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if signed_in? %>
          <% if current_user %>
            <li><%= link_to "New Product", new_product_path %></li>
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <% elsif current_admin %>
            <li><%= link_to "Edit Profile", edit_admin_registration_path %></li>
            <li><%= link_to "Logout", destroy_admin_session_path, method: :delete %></li>
          <% end %>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Sign Up <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "as admin", new_admin_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "as guest", new_user_registration_path %></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Login <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "as admin", new_admin_session_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "as guest", new_user_session_path %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProductsGrid</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navigation' %>

  <% if notice %>
      <div class="alert alert-success text-center">
        <%= notice %>
      </div>
  <% end %>

  <% if alert %>
    <div class="alert alert-danger text-center">
      <%= alert %>
    </div>
  <% end %>

  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/products/_form.html.erb
<%= form_for @product, html: { multipart: true } do |f| %>
  <% if current_admin %>
    <div class="form-group">
      <%= f.check_box :is_pro %>
      <%= f.label :is_pro, "Pro Product?" %>
    </div>
  <% else %>
    <div class="form-group">
      <%= f.label :name %><br>
      <%= f.text_field :name, autofocus: true, class: "form-control" %><br>
    </div>

    <div class="form-group">
      <%= f.label :description %><br>
      <%= f.text_area :description, class: "form-control" %><br>
    </div>

    <div class="form-group">
      <%= f.label :image %><br>
      <%= f.file_field :image %><br>
    </div>
  <% end %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/products/_home.html.erb
<div class="jumbotron">
  <h1>Hello!</h1>
  <p>My name is ProductsGrid and here you can add your own products and look at other!</p>
  <%= link_to "Register", new_user_registration_path, class: "btn btn-primary btn-lg" %>
  <%= link_to "Login", new_user_session_path, class: "btn btn-success btn-lg" %>
</div>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render 'form' %>

app/views/products/index.html.erb
<% if signed_in? %>
  <h1 class="text-center">All Products</h1><br>
  <div class="row">
    <% @products.each do |product| %>
      <div class="col-md-4">
        <div class="thumbnail">
          <%= link_to product do %>
            <%= image_tag product.image.url(:medium) %>
          <% end %>
          <div class="caption">
            <h3>
              <%= product.name %>
              <% if product.is_pro? %>
                <span class="badge">PRO</span>
              <% end %>
            </h3>
            <p><%= product.description %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <%= render 'home' %>
<% end %>



app/views/products/new.html.erb
<h1>Add Product</h1>

<%= render 'form' %>

app/views/products/show.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading center">
        <h3 class="panel-title text-center">
          <%= @product.name %>
          <% if @product.is_pro? %>
            <span class="badge">PRO</span>
          <% end %>
        </h3>
      </div>
      <div class="panel-body text-center">
        <%= image_tag @product.image.url(:large) %><br>
        <%= @product.description %><br>
        <% if current_admin %>
          <%= link_to "Edit", edit_product_path, class: "btn btn-primary pull-right" %>
        <% end %>
      </div>
    </div>
  </div>
</div>